plugins {
    id 'com.android.application'
}

android {
    namespace 'com.monkeyphone.trackmonk'
    compileSdk 34

    defaultConfig {
        applicationId "com.monkeyphone.trackmonk"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0.0"

        manifestPlaceholders = [
            hostName: "trackmonk.monkeyfon.com",
            defaultUrl: "https://trackmonk.monkeyfon.com/index.html",
            launcherName: "TrackMonk",
            assetStatements: '[{"relation": ["delegate_permission/common.handle_all_urls"], "target": {"namespace": "web", "site": "https://trackmonk.monkeyfon.com"}}]'
        ]
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.browser:browser:1.7.0'
    implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.5.0'
}
